# Generated by Django 6.0.3 on 2026-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
